version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - OLLAMA_URL=http://ollama:11434
      - DOCUMENT_STORE=${DOCUMENT_STORE:-FAISS}
    volumes:
      - ./data:/app/data

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: streamlit run docgpt/client/app.py
    ports:
      - "8501:8501"
    depends_on:
      - app

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: